language: python

jobs:
  include:
    - os: linux
      dist: focal
      python: 3.8
    - os: linux
      dist: focal
      python: 3.9
    - os: linux
      dist: focal
      python: 3.10
    - os: linux
      dist: focal
      python: 3.11
    # Windowsは最新のPythonバージョンのみテストする。
    # 最新でないPythonバージョンのテストはすでに実施できているので。
    # このテストはWindows特有のバグが発生しないことを確認する
    - os: windows
      python: 3.11
      language: shell  # 'language: python' is an error on Travis CI Windows
      install:
        - choco install python --version 3.11
        - python -m pip install --upgrade pip
        - pip3 install "poetry<1.5"
        - travis_retry poetry install --only main,linter,test,typeshed
      env: PATH=/c/Python311:/c/Python311/Scripts:$PATH

install:
  # pipをアップグレードする理由: pipのバージョンが古いと、pillowなど環境ごとにwheelを提供しているライブラリのインストールに失敗する可能性があるため
  - pip install pip --upgrade
  - pip install "poetry<1.5"
  # 必要なライブラリだけインストールする
  - travis_retry poetry install --only main,linter,test,typeshed

script:
   - make lint
     # webapiにアクセスするテストは実行しないようにする
   - poetry run pytest -n auto -m "not access_webapi"

branches:
  only:
  - main
env:
  # `poetry install`時に`Max retries exceeded with`が発生しないようにするため、タイムアウト時間を指定する
  # 認証情報がテストに失敗するため、適当な認証情報を設定する
  - PIP_DEFAULT_TIMEOUT=300 ANNOFAB_USER_ID=foo ANNOFAB_PASSWORD=bar

cache: pip
