dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  # pipをアップグレードする理由: pipのバージョンが古いと、pillowなど環境ごとにwheelを提供しているライブラリのインストールに失敗する可能性があるため
  - pip install pip --upgrade
  - pip install "poetry<1.4"
  - travis_retry poetry install
script:
   - make lint
     # webapiにアクセスするテストは実行しないようにする
   - poetry run pytest -n auto -m "not access_webapi"

branches:
  only:
  - main
env:
  # `poetry install`時に`Max retries exceeded with`が発生しないようにするため、タイムアウト時間を指定する
  # 認証情報がテストに失敗するため、適当な認証情報を設定する
  - PIP_DEFAULT_TIMEOUT=300 ANNOFAB_USER_ID=foo ANNOFAB_PASSWORD=bar

cache: pip
