dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install poetry && poetry install
script:
   - poetry run flake8 annofabcli
   - poetry run mypy annofabcli
   - poetry run pylint  --jobs=0 annofabcli
   - poetry run pytest tests/test_local*.py
branches:
  only:
  - master
