language: python
dist: focal

script:
  - poetry run pytest -n auto -m "not access_webapi"

jobs:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12
      script:
        - poetry run pytest -n auto -m "not access_webapi"
        # 開発環境と同じバージョンではlintを実行する
        - make lint

install:
  # pipをアップグレードする理由: pipのバージョンが古いと、pillowなど環境ごとにwheelを提供しているライブラリのインストールに失敗する可能性があるため
  - pip install pip --upgrade
  - pip install "poetry<1.9"
  - travis_retry poetry install

branches:
  only:
  - main
env:
  # `poetry install`時に`Max retries exceeded with`が発生しないようにするため、タイムアウト時間を指定する
  # 認証情報がテストに失敗するため、適当な認証情報を設定する
  - PIP_DEFAULT_TIMEOUT=300 ANNOFAB_USER_ID=foo ANNOFAB_PASSWORD=bar

cache: pip
