dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install poetry && poetry install
script:
   - make lint
   - poetry run pytest tests/test_local*.py
branches:
  only:
  - master
