dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  # pipをアップグレードする理由: pipのバージョンが古いと、pillowなど環境ごとにwheelを提供しているライブラリのインストールに失敗する可能性があるため
  - pip install pip poetry --upgrade
  - travis_retry poetry install
script:
   - make lint
   - poetry run pytest tests/test_local*.py
branches:
  only:
  - main
env:
  # `poetry install`時に`Max retries exceeded with`が発生しないようにするため、タイムアウト時間を指定する
  - PIP_DEFAULT_TIMEOUT=300

cache: pip
