from __future__ import annotations

import argparse
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from annofabcli.__main__ import create_parser

OUTPUT_PATH = Path(__file__).parents[1] / "skills" / "annofab-cli" / "references" / "command-index.md"
"""生成するコマンド索引のパス。"""


@dataclass(frozen=True)
class Command:
    """annofab-cliのコマンド。"""

    names: tuple[str, ...]
    """`annofabcli`を除いたコマンド名の並び。"""

    description: str
    """コマンドの簡潔な説明。"""


@dataclass(frozen=True)
class CommandGroup:
    """annofab-cliのトップレベルコマンドと配下の末端コマンド。"""

    name: str
    """トップレベルコマンド名。"""

    description: str
    """トップレベルコマンドの簡潔な説明。"""

    commands: tuple[Command, ...]
    """このグループに属する末端コマンド。"""


def _normalize_description(description: str | None) -> str:
    """コマンドの説明をMarkdownの1行に整形する。

    Args:
        description: argparseに登録されたコマンドの説明。

    Returns:
        連続する空白を1個にまとめた説明。
    """
    if description is None:
        return "説明はありません。"
    return " ".join(description.split())


def _find_subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    """parserに登録されたサブパーサーのactionを返す。

    Args:
        parser: 検索対象のArgumentParser。

    Returns:
        サブパーサーのaction。存在しない場合はNone。
    """
    return next((action for action in parser._actions if isinstance(action, argparse._SubParsersAction)), None)  # noqa: SLF001


def _get_command_help_by_name(action: argparse._SubParsersAction) -> dict[str, str]:
    """サブコマンド名ごとの簡潔な説明を返す。

    Args:
        action: サブパーサーのaction。

    Returns:
        サブコマンド名と説明のマッピング。
    """
    return {choice.dest: _normalize_description(choice.help) for choice in action._choices_actions}  # noqa: SLF001


def _collect_leaf_commands(parser: argparse.ArgumentParser, names: tuple[str, ...], description: str) -> tuple[Command, ...]:
    """parser配下の末端コマンドを再帰的に収集する。

    Args:
        parser: 検索対象のArgumentParser。
        names: 現在のparserまでのコマンド名。
        description: 現在のparserの簡潔な説明。

    Returns:
        末端コマンドの一覧。
    """
    subparsers_action = _find_subparsers_action(parser)
    if subparsers_action is None:
        return (Command(names=names, description=description),)

    help_by_name = _get_command_help_by_name(subparsers_action)
    result: list[Command] = []
    for name, child_parser in subparsers_action.choices.items():
        result.extend(_collect_leaf_commands(child_parser, (*names, name), help_by_name[name]))
    return tuple(result)


def collect_command_groups(parser: argparse.ArgumentParser) -> tuple[CommandGroup, ...]:
    """annofab-cliのコマンドをトップレベルコマンドごとに収集する。

    Args:
        parser: annofab-cliのルートArgumentParser。

    Returns:
        コマンドグループの一覧。

    Raises:
        ValueError: ルートArgumentParserにサブコマンドが存在しない場合。
    """
    subparsers_action = _find_subparsers_action(parser)
    if subparsers_action is None:
        msg = "ルートArgumentParserにサブコマンドが存在しません。"
        raise ValueError(msg)

    help_by_name = _get_command_help_by_name(subparsers_action)
    return tuple(
        CommandGroup(
            name=name,
            description=help_by_name[name],
            commands=_collect_leaf_commands(child_parser, (name,), help_by_name[name]),
        )
        for name, child_parser in subparsers_action.choices.items()
    )


def build_command_index(command_groups: Sequence[CommandGroup]) -> str:
    """コマンドグループからMarkdown形式の索引を生成する。

    Args:
        command_groups: コマンドグループの一覧。

    Returns:
        Markdown形式のコマンド索引。
    """
    lines = [
        "<!-- This file is generated by scripts/generate_skill_command_index.py. Do not edit manually. -->",
        "",
        "# annofab-cliコマンド索引",
        "",
        "このファイルは、annofab-cliが提供するコマンドとその概要を確認するための索引です。",
        "オプションや引数の詳細は、使用する環境で索引に記載されたコマンドに`--help`を付けて実行し、確認してください。",
    ]

    for group in command_groups:
        lines.extend(["", f"## {group.name}", "", group.description, ""])
        for command in group.commands:
            invocation = " ".join(("annofabcli", *command.names))
            lines.append(f"- `{invocation}`: {command.description}")

    return "\n".join(lines) + "\n"


def is_command_index_current(command_index: str, output_path: Path) -> bool:
    """生成対象のコマンド索引が最新かどうかを返す。

    Args:
        command_index: argparseの定義から生成したコマンド索引。
        output_path: 確認対象のコマンド索引のパス。

    Returns:
        ファイルが存在し、生成した内容と一致する場合はTrue。
    """
    return output_path.is_file() and output_path.read_text(encoding="utf-8") == command_index


def main(arguments: Sequence[str] | None = None) -> None:
    """argparseの定義からスキル用のコマンド索引を生成する。

    Args:
        arguments: コマンドライン引数。Noneの場合はプロセスの引数を使用する。

    Returns:
        None
    """
    parser = argparse.ArgumentParser(description="スキル用のコマンド索引を生成します。")
    parser.add_argument("--check", action="store_true", help="コマンド索引を更新せず、argparseの定義と一致するか確認します。")
    args = parser.parse_args(arguments)

    command_index = build_command_index(collect_command_groups(create_parser()))
    if args.check:
        if not is_command_index_current(command_index, OUTPUT_PATH):
            msg = f"{OUTPUT_PATH}がargparseの定義と一致しません。\n`uv run python scripts/generate_skill_command_index.py`を実行してください。"
            raise SystemExit(msg)
        return

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(command_index, encoding="utf-8")


if __name__ == "__main__":
    main()
